### PR TITLE
switch from graph_objects to px

### PR DESCRIPTION
**Pull request by nicolaskruchten**
Let's see if Kaleido works "out of the box" here with the rendering framework! in principle there's no need for the `Image(fig.to_image(format="png", width=900, height=900))` stuff :)

### CODE REVIEW

**Comment by tdhopper** [comment]
@nicolaskruchten Awesome! Does this look right? 5f636f0dda78390aa9c727b6--pythonplot-com.netlify.app

**Comment by nicolaskruchten** [comment]
Looks as intended!

**Comment by nicolaskruchten** [comment]
I might suggest rendering smaller than 900x900 as the as the fonts look really small... I can tack on a couple of commits here if the overall approach is right :)

**Comment by tdhopper** [comment]
@nicolaskruchten sure

**Comment by nicolaskruchten** [comment]
Awesome! Thanks, this lets PX shine at what it's good at ;) PX initially stood for Plotly Explore actually but we changed it to Express because it's not really just for EDA.

**Pull request merged**
